### ISSUE TITLE
Git push prompts for your password

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/git-basics-lab#17]
When trying to push my changes to my remote branch I am prompted to sign in to GitHub and when I logged in using my credentials I get an unauthorized error and my lab is still failing with one error that my changes have not been pushed.

```
command: git-basics-lab-v-000>git push origin master
Logon failed, use ctrl+c to cancel basic credential prompt.
Username for 'https://github.com': sequina
Password for 'https://sequina@github.com':
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/sequina/git-basics-lab-v-000.git/'
```

**Comment by ihollander** [comment]
Thanks for raising this issue. Based on your description, it sounds like the issue may be related to your environment setup rather than with the lesson itself or the instructions. The curriculum team monitors these issues so that we can fix typos and bugs in the curriculum, but we aren't equipped to provide support.

To get help with your question, you should either: 

- Reach out to your instructor (if you've started the program and have an instructor)
- Use the [#js-prework-support](https://flatiron-school.slack.com/archives/C01KEEVJU3Y) Slack channel (if you're working on the prework)
- Use the [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit) feature in Canvas to connect with a Technical Coach on the Academic Success Team

Please re-open this issue if you believe the lesson needs to be updated.

Hope you are able to get this resolved!
