### ISSUE TITLE
The git labs are not processing the learn code

### ISSUE THREAD

**Issue by CGonzalez0115** [learn-co-curriculum/git-basics-lab#4]
When running the learn code on both the Git Basic Lab and the Merge conficts lab it does not return and test report so it is not letting me complete those two labs.

**Comment by sgharms** [comment]
This issue would be perfect for the [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ) feature, where the [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) (on [supported tracks](http://help.learn.co/instructional-support/receiving-course-support/does-my-program-or-course-have-technical-coach-support)) and fellow community members can help you figure it out. We probably need to work with you in real-time to figure out what's going on: whether the problem is an issue in the Learn Platform (technology isn't working) or whether it's in the curriculum (challenge materials don't work).

If you could please use AAQ to debug this and provide the coach this issue as a reference, we'll be able to handle getting the right people on this.

If, after consulting the Help Center and AAQ, you still feel that this is an issue with the curriculum itself, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).
